// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: common/response_code.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Code int32

const (
	//general
	Code_Ok              Code = 0
	Code_InternalError   Code = 1
	Code_InvalidParams   Code = 2
	Code_OperationFailed Code = 3
	Code_NotFindData     Code = 4
	//auth
	Code_UserExisting               Code = 1001
	Code_IncorrectAccountOrPassword Code = 1002 //gate
)

// Enum value maps for Code.
var (
	Code_name = map[int32]string{
		0:    "Ok",
		1:    "InternalError",
		2:    "InvalidParams",
		3:    "OperationFailed",
		4:    "NotFindData",
		1001: "UserExisting",
		1002: "IncorrectAccountOrPassword",
	}
	Code_value = map[string]int32{
		"Ok":                         0,
		"InternalError":              1,
		"InvalidParams":              2,
		"OperationFailed":            3,
		"NotFindData":                4,
		"UserExisting":               1001,
		"IncorrectAccountOrPassword": 1002,
	}
)

func (x Code) Enum() *Code {
	p := new(Code)
	*p = x
	return p
}

func (x Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Code) Descriptor() protoreflect.EnumDescriptor {
	return file_common_response_code_proto_enumTypes[0].Descriptor()
}

func (Code) Type() protoreflect.EnumType {
	return &file_common_response_code_proto_enumTypes[0]
}

func (x Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Code.Descriptor instead.
func (Code) EnumDescriptor() ([]byte, []int) {
	return file_common_response_code_proto_rawDescGZIP(), []int{0}
}

type ResponseCode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code Code   `protobuf:"varint,1,opt,name=code,proto3,enum=common.Code" json:"code,omitempty"`
	Err  string `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *ResponseCode) Reset() {
	*x = ResponseCode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_response_code_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseCode) ProtoMessage() {}

func (x *ResponseCode) ProtoReflect() protoreflect.Message {
	mi := &file_common_response_code_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseCode.ProtoReflect.Descriptor instead.
func (*ResponseCode) Descriptor() ([]byte, []int) {
	return file_common_response_code_proto_rawDescGZIP(), []int{0}
}

func (x *ResponseCode) GetCode() Code {
	if x != nil {
		return x.Code
	}
	return Code_Ok
}

func (x *ResponseCode) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

var File_common_response_code_proto protoreflect.FileDescriptor

var file_common_response_code_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x22, 0x42, 0x0a, 0x0c, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x20, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x63, 0x6f, 0x64, 0x65,
	0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x72, 0x72, 0x2a, 0x8e, 0x01, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x6b, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x49, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d,
	0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x10, 0x02, 0x12,
	0x13, 0x0a, 0x0f, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x61, 0x69, 0x6c,
	0x65, 0x64, 0x10, 0x03, 0x12, 0x0f, 0x0a, 0x0b, 0x4e, 0x6f, 0x74, 0x46, 0x69, 0x6e, 0x64, 0x44,
	0x61, 0x74, 0x61, 0x10, 0x04, 0x12, 0x11, 0x0a, 0x0c, 0x55, 0x73, 0x65, 0x72, 0x45, 0x78, 0x69,
	0x73, 0x74, 0x69, 0x6e, 0x67, 0x10, 0xe9, 0x07, 0x12, 0x1f, 0x0a, 0x1a, 0x49, 0x6e, 0x63, 0x6f,
	0x72, 0x72, 0x65, 0x63, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4f, 0x72, 0x50, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x10, 0xea, 0x07, 0x42, 0x10, 0x5a, 0x0e, 0x2f, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x3b, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_common_response_code_proto_rawDescOnce sync.Once
	file_common_response_code_proto_rawDescData = file_common_response_code_proto_rawDesc
)

func file_common_response_code_proto_rawDescGZIP() []byte {
	file_common_response_code_proto_rawDescOnce.Do(func() {
		file_common_response_code_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_response_code_proto_rawDescData)
	})
	return file_common_response_code_proto_rawDescData
}

var file_common_response_code_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_response_code_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_response_code_proto_goTypes = []interface{}{
	(Code)(0),            // 0: common.code
	(*ResponseCode)(nil), // 1: common.responseCode
}
var file_common_response_code_proto_depIdxs = []int32{
	0, // 0: common.responseCode.code:type_name -> common.code
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_common_response_code_proto_init() }
func file_common_response_code_proto_init() {
	if File_common_response_code_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_response_code_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseCode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_response_code_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_response_code_proto_goTypes,
		DependencyIndexes: file_common_response_code_proto_depIdxs,
		EnumInfos:         file_common_response_code_proto_enumTypes,
		MessageInfos:      file_common_response_code_proto_msgTypes,
	}.Build()
	File_common_response_code_proto = out.File
	file_common_response_code_proto_rawDesc = nil
	file_common_response_code_proto_goTypes = nil
	file_common_response_code_proto_depIdxs = nil
}
